
# our dev database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furniture_store?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver: com.mysql.jdbc.Driver
    # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.store.entity  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus
mybatis-plus:
  mapper-locations: com/example/demo/mapping/*.xml
  configuration:
    #开启MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  # swagger prefix defind in common-jar
swagger:
  title: interface-test
  description: api for interface-test
  version: 1.1.0
  termsOfServiceUrl: https://localhost:8082
  apiBasePackage: com.example.store.controller
server:
  port: 8183


mapper:
  mappers: com.example.store.mapper.CommonMapper
  identity: MYSQL
